### PR TITLE
🐛 BUG: numbered nested toctrees were unordered

### LINKED ISSUE #14: Wrong chapter numbers when toctrees located in different .rst files
**Describe the bug**

I'm using (numbered) `toctree`s in multiple files. I include these files in the toplevel (unumbered) `toctree`. When I do this, chapter numbers are not properly ordered (the first chapter to be numbered is not in part 1).

**To Reproduce**

Assume the following project structure:

```
index.rst
unumbered_chapter.rst
part1/index.rst
part1/chapter1.rst
part1/chapter2.rst
part2/index.rst
part2/chapter3.rst
part3/index.rst
part3/chapter4.rst
```

Contents of `index.rst` are:
```
.. toctree::
    :maxdepth: 2

    unumbered_chapter
    part1/index
    part2/index
    part3/index
```

Contents of `part1/index.rst` are:
```
.. toctree::
    :numbered:

    chapter1
    chapter2
```

Contents of `part2/index.rst` and `part3/index.rst` are analogous.

In my case, I get the toplevel TOC messed up, like:
```
* Part 1
  3. Chapter 1
  4. Chapter 2
* Part 2
  1. Chapter 3
* Part 3
  2. Chapter 4
```

Note: the problem does not always happen, but it does in most of the `sphinx-build`s.

**Expected behavior**

The output should be:
```
* Part 1
  1. Chapter 1
  2. Chapter 2
* Part 2
  3. Chapter 3
* Part 3
  4. Chapter 4
```

**Environment**

- Running Sphinx v3.2.1
- Python Version 3.5.2:
- Not using `jupyter-book`
- Operating System: Linux rti-10636 4.15.0-118-generic #119~16.04.1-Ubuntu SMP Tue Sep 8 14:54:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by AakashGfude**
fixes https://github.com/executablebooks/sphinx-multitoc-numbering/issues/14

Thanks, @guyikcgg for the issue. Also, is it fine if I steal your [test repo](https://github.com/guyikcgg/sphinx-multitoc-numbering-issue14) for this bug as a test case for this repo? :P. Have kept your name as the author. 

Probably it would be better though I think if you send a PR with that test folder?

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude do you need any other test cases? If `unumbered` is lower down in the toc (for example) with that matter?

**Review by mmcky — APPROVED** [review]

**Comment by AakashGfude** [comment]
@mmcky If the parent toctree is `unnumbered` then all's good.
If the parent is a numbered toctree, then the child unnumbered gets numbered as well. Which is expected behavior? unless the user specifically mentions to not make it unnumbered (specified by a config ?).

**Comment by AakashGfude** [comment]
Ahh, there is already an ongoing discussion about having the ability to not number sections https://github.com/executablebooks/jupyter-book/issues/546#issuecomment-654464231 , will try to implement it in this repo.

**Comment by AakashGfude** [comment]
I will merge this for now.  @guyikcgg let us know if you are happy with us using your test folder.

**Comment by guyikcgg** [comment]
@AakashGfude Thank you so much for fixing this issue!! I'm glad my reproducer was useful, and you use it as a test. Thank you for keeping my name in it :grinning:

**Pull request merged**
